export const genres = [
    "fantasy",
    "science fiction",
    "horror",
    "western",
    "romance",
    "thriller",
    "mystery",
    "detective",
    "dystopia",
    "adventure",
    "memoir",
    "biography",
    "play",
    "musical",
    "theatre",
]